### ISSUE TITLE
请问Loss这么小正常吗？

### ISSUE THREAD

**Issue by Surrin1999** [zlearh/water_image#2]
![image](https://user-images.githubusercontent.com/37960540/153807826-f528780a-46be-4462-ab2a-25083c296f05.png)
使用repo中提供的VGG权重和默认的训练数据进行训练，loss有点小

**Comment by zlearh** [comment]
这是正常现象。
感知损失的值虽然很小，但是我在后续的消融实验中发现，如果去除感知损失函数，图像的处理效果是会出现明显下降。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zlearh/Water_Net-code_pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月14日(星期一) 中午1:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zlearh/Water_Net-code_pytorch] 请问Loss这么小正常吗？ (Issue #2)





 

 使用repo中提供的VGG权重和默认的训练数据进行训练，loss有点小
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Surrin1999** [comment]
> 

感谢您的答复，之前我看城大的一位学长的论文提到类似的loss，感知损失好像是可以防止过度增强，保证内容上和gt相似的
![image](https://user-images.githubusercontent.com/37960540/153809750-841936a0-bfb0-40f4-a36e-0971685e3388.png)
![image](https://user-images.githubusercontent.com/37960540/153809960-23cf18fd-e72d-4d38-a2ec-ece5c5ece756.png)
