### ISSUE TITLE
请问一下提供的VGG权重是在哪个数据集上训练过的呢？

### ISSUE THREAD

**Issue by Surrin1999** [zlearh/water_image#3]
我看了下代码中的VGG似乎不是标准的VGG19复现，就尝试采用pytorch官网提供的VGG19[预训练权重](https://download.pytorch.org/models/vgg19_bn-c79401a0.pth)来进行训练，但是感知损失比起您提供的权重大了很多
![image](https://user-images.githubusercontent.com/37960540/154204432-9796f0ba-55a5-4a65-8a1c-8b10284400f6.png)
请问一下您当时是在哪个数据集上进行的预训练呢？

**Comment by zlearh** [comment]
我所使用的VGG模型数据集UIEB做的预训练。
论文中用标准的VGG网络，你可以按照论文来。
我原先也想用标准的VGG网络，但是后面发现自己写的VGG网络效果差距不是很大，就没去改。




------------------&nbsp;原始邮件 ------------------
发件人:                                                                                                                        "zlearh/Water_Net-code_pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月16日(星期三) 中午1:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zlearh/Water_Net-code_pytorch] 请问一下提供的VGG权重是在哪个数据集上训练过的呢？ (Issue #3)





 
我看了下代码中的VGG似乎不是标准的VGG19复现，就尝试采用pytorch官网提供的VGG19预训练权重来进行训练，但是感知损失比起您提供的权重大了很多
 
 请问一下您当时是在哪个数据集上进行的预训练呢？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Surrin1999** [comment]
> 我所使用的VGG模型数据集UIEB做的预训练。 论文中用标准的VGG网络，你可以按照论文来。 我原先也想用标准的VGG网络，但是后面发现自己写的VGG网络效果差距不是很大，就没去改。
> […](#)
> ------------------&nbsp;原始邮件 ------------------ 发件人: "zlearh/Water_Net-code_pytorch" ***@***.***&gt;; 发送时间:&nbsp;2022年2月16日(星期三) 中午1:53 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[zlearh/Water_Net-code_pytorch] 请问一下提供的VGG权重是在哪个数据集上训练过的呢？ (Issue #3) 我看了下代码中的VGG似乎不是标准的VGG19复现，就尝试采用pytorch官网提供的VGG19预训练权重来进行训练，但是感知损失比起您提供的权重大了很多 请问一下您当时是在哪个数据集上进行的预训练呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感谢！
