### ISSUE TITLE
请问当时您的VGG在UIEB上训练了多少epoch？

### ISSUE THREAD

**Issue by Surrin1999** [zlearh/water_image#4]
我正在迁移WaterNet作为我的模型的一个模块，需要在低版本的pytorch中加载您的vgg权重，但是在加载您高版本的权重文件时我的pytorch会报错，所以应该是要在低版本的pytorch重新训练一遍vgg，请问您的vgg在UIEB上训练了多少个epoch呢？

**Comment by zlearh** [comment]
大约100epoch左右。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zlearh/Water_Net-code_pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 晚上11:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zlearh/Water_Net-code_pytorch] 请问当时您的VGG在UIEB上训练了多少epoch？ (Issue #4)





 
我正在迁移WaterNet作为我的模型的一个模块，需要在低版本的pytorch中加载您的vgg权重，但是在加载您高版本的权重文件时我的pytorch会报错，所以应该是要在低版本的pytorch重新训练一遍vgg，请问您的vgg在UIEB上训练了多少个epoch呢？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
